[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.19.4"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/bal7hazar/types-cairo"

[workspace.dependencies]
snforge_std = "0.61.0"

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
